### ISSUE TITLE
ToDo: anpassung an ec-verwaltung

### ISSUE THREAD

**Issue by mathe42** [EC-Nordbund/gotrue-js#1]
- [ ] API calls anpassen
- [ ] auf fetch umstellen?
- [ ] refresh token entfernen bzw. wenn aufgerufen auto logout
- [ ] ...
